name: "GitHub Actions Weather Email Bot"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"

jobs:
  weather-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: "Install requirements"
        run: pip install -r ./requirements.txt
      - name: "Working"
        run: bash ./weather-emailbot/main.sh
      - name: "Send mail"
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Weather Report
          body: file://ToSendEmail.txt
          to: ${{ secrets.MAIL_RECEIVER }}
          from: GitHub Actions
          content_type: text/plain
